spring.application.name=jirac

spring.datasource.url=jdbc:postgresql://localhost:5432/jirac
spring.datasource.username=postgres
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.problemdetails.enabled=true
